remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

title: "Md Walidur Rahman"
description: "IT expert"
minimal_mistakes_skin: "air"

author:
  name: "Md Walidur Rahman"
  avatar: "/path/to/avatar.jpg" # Replace with the actual path to your profile picture
  bio: "IT expert and enthusiast"
