# _config.yml

remote_theme: "mmistakes/minimal-mistakes@4.22.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

title: "Md Walidur Rahman's Tech Hub"
description: "Insights, tutorials, and news on IT and software development"
baseurl: ""
url: "https://mdwalidurrahman.com"
minimal_mistakes_skin: "air"

author:
  name: "Md Walidur Rahman"
  avatar: "/assets/images/profile.jpg"
  bio: "IT expert, software developer, and tech enthusiast sharing tips and insights."

# Navigation setup (optional, but recommended)
header:
  navigation:
    - title: "Home"
      url: /
    - title: "CV"
      url: /cv/

# Footer (optional)
footer:
  social:
    - title: "GitHub"
      url: "https://github.com/mdwalidurrahman"
      icon: "fab fa-github"

markdown: kramdown
highlighter: rouge
permalink: pretty

seo:
  type: "Person"
  name: "Md Walidur Rahman"
  description: "IT expert and technology enthusiast dedicated to sharing insights and expertise."
