# _config.yml

remote_theme: "mmistakes/minimal-mistakes@4.22.0"

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

title: "Md Walidur Rahman's Tech Hub"
description: "Insights, tutorials, and news on IT and software development"
baseurl: ""        # The subpath of your site, e.g. /blog
url: "https://mdwalidurrahman.com"   # The base hostname & protocol for your site
minimal_mistakes_skin: "air"

author:
  name: "Md Walidur Rahman"
  avatar: "/assets/images/profile.jpg"   # Update this to your actual profile picture path
  bio: "IT expert, software developer, and tech enthusiast sharing tips and insights."
  email: "contact@mdwalidurrahman.com"
  location: "Dhaka, Bangladesh"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/mdwalidurrahman"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://linkedin.com/in/mdwalidurrahman"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/mdwalidurrahman"

header:
  navigation:
    - title: "Home"
      url: /
    - title: "About"
      url: /about/
    - title: "Blog"
      url: /blog/
    - title: "Projects"
      url: /projects/

footer:
  social:
    - title: "GitHub"
      url: "https://github.com/mdwalidurrahman"
      icon: "fab fa-github"
    - title: "LinkedIn"
      url: "https://linkedin.com/in/mdwalidurrahman"
      icon: "fab fa-linkedin"
    - title: "Twitter"
      url: "https://twitter.com/mdwalidurrahman"
      icon: "fab fa-twitter"

markdown: kramdown
highlighter: rouge
permalink: pretty

seo:
  type: "Person"
  name: "Md Walidur Rahman"
  description: "IT expert and technology enthusiast dedicated to sharing insights and expertise."
